#!/usr/bin/php
<?php
/* https://blog.programster.org/creating-phar-files */

$pharFile = basename(__DIR__) . '.phar';

// clean up
if (file_exists($pharFile)) 
{
    unlink($pharFile);
}

if (file_exists($pharFile . '.gz')) 
{
    unlink($pharFile . '.gz');
}

// create phar
$phar = new Phar($pharFile);

// start buffering. Mandatory to modify stub to add shebang
$phar->startBuffering();

// Create the default stub from index.php entrypoint
$defaultStub = $phar->createDefaultStub('index.php');

// Add the rest of the apps files
// $phar->buildFromDirectory(__DIR__ . '/vendor');
$phar->buildFromDirectory(__DIR__ . '/lib');
$phar->buildFromDirectory(__DIR__ . '/app');

// Customize the stub to add the shebang
$stub = "#!/usr/bin/php\n" . $defaultStub . "__HALT_COMPILER();\n";

// Add the stub
$phar->setStub($stub);

$phar->stopBuffering();

// plus - compressing it into gzip  
$phar->compressFiles(Phar::GZ);

// # Make the file executable
chmod(__DIR__ . '/' . $pharFile, 0770);

echo "$pharFile successfully created" . PHP_EOL;
